server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-server
    api-b:
      path: /api-b/**
      serviceId: feign-server
